version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # Оставь порт, если хочешь подключаться к БД с хоста (psql/IDE).
    # Если не нужно — можешь удалить блок ports.
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subscriptions"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Путь к файлу КОНФИГА внутри репозитория, который надо запечь в образ
        CONFIG_FILE: ./config/config.yaml
    # опционально: имя итогового образа
    image: subscription:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  pgdata:
