openapi: 3.0.0
info:
  title: Subscription API
  version: "1.0"
  description: API для управления подписками пользователей

servers:
  - url: http://localhost:8080/

paths:
  /subscriptions:
    post:
      summary: Создать подписку
      description: Создает новую подписку для пользователя.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionCreateRequest'
      responses:
        '201':
          description: Успешно создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Неверный запрос
        '500':
          description: Внутренняя ошибка

    get:
      summary: Получить список подписок
      description: Получить список подписок с возможностью фильтрации.
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
            format: uuid
          required: false
          description: Идентификатор пользователя (UUID)
        - in: query
          name: service_name
          schema:
            type: string
          required: false
          description: Фильтр по названию сервиса
      responses:
        '200':
          description: Список подписок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '500':
          description: Внутренняя ошибка

  /subscriptions/{id}:
    get:
      summary: Получить подписку по ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Подписка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Неверный ID
        '404':
          description: Не найдено

    put:
      summary: Обновить подписку
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionUpdateRequest'
      responses:
        '200':
          description: Успешно обновлено
        '400':
          description: Неверный запрос
        '500':
          description: Внутренняя ошибка

    delete:
      summary: Удалить подписку
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Успешно удалено
        '400':
          description: Неверный ID
        '500':
          description: Внутренняя ошибка

  /subscriptions/summary:
    get:
      summary: Сумма подписок за период
      description: Считает сумму всех подписок за период, можно фильтровать по пользователю и сервису.
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
            format: uuid
          required: false
          description: Идентификатор пользователя (UUID)
        - in: query
          name: service_name
          schema:
            type: string
          required: false
        - in: query
          name: from
          schema:
            type: string
            example: "01-2024"
            description: Начало периода, формат MM-YYYY
          required: true
        - in: query
          name: to
          schema:
            type: string
            example: "12-2024"
            description: Конец периода, формат MM-YYYY
          required: true
      responses:
        '200':
          description: Сумма
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
        '400':
          description: Неверные параметры
        '500':
          description: Внутренняя ошибка

components:
  schemas:
    Subscription:
      type: object
      properties:
        id:
          type: integer
          example: 1
        service_name:
          type: string
          example: "Netflix"
        price:
          type: integer
          example: 499
        user_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        start_date:
          type: string
          example: "01-2024"
        end_date:
          type: string
          nullable: true
          example: "12-2024"

    SubscriptionCreateRequest:
      type: object
      required: [service_name, price, user_id, start_date]
      properties:
        service_name:
          type: string
          example: "Netflix"
        price:
          type: integer
          example: 499
        user_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        start_date:
          type: string
          example: "01-2025"
        end_date:
          type: string
          nullable: true
          example: "12-2025"

    SubscriptionUpdateRequest:
      type: object
      required: [service_name, price, user_id, start_date]
      properties:
        service_name:
          type: string
          example: "yandex"
        price:
          type: integer
          example: 789
        user_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        start_date:
          type: string
          example: "01-2025"
        end_date:
          type: string
          nullable: true
          example: "12-2025"
